# Generated by Django 3.1.14 on 2023-04-13 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_remove_pokemon_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokedex_num',
            field=models.IntegerField(default=0),
        ),
    ]
