# Generated by Django 3.1.14 on 2023-04-17 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0002_auto_20230417_0356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemonentity',
            name='pokedex_num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon', verbose_name='id покемона в покедексе'),
        ),
    ]
