# Generated by Django 3.1.14 on 2023-04-17 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0004_auto_20230417_2112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Lat',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='Lon',
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='latitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='longitude',
            field=models.FloatField(blank=True, null=True, verbose_name='Долгота'),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='poke_image_local',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Путь к картинке на вашем устройстве'),
        ),
    ]
