# Generated by Django 3.1.14 on 2023-04-17 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230417_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='evolutions',
        ),
        migrations.RemoveField(
            model_name='pokemonentity',
            name='pokedex_num',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='previous_evolution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_evolutions', to='pokemon_entities.pokemon', verbose_name='Предшествующая эволюция'),
        ),
        migrations.AddField(
            model_name='pokemonentity',
            name='pokemon',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, related_name='Pokemons', to='pokemon_entities.pokemon', verbose_name='id покемона в покедексе'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Русское название'),
        ),
    ]
