# Generated by Django 3.1.14 on 2023-04-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0005_auto_20230414_0232'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='poke_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
