# Generated by Django 3.1.14 on 2023-04-17 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0006_auto_20230418_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='poke_image_link',
        ),
    ]
