# Generated by Django 3.1.14 on 2023-04-19 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0007_remove_pokemon_poke_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='poke_image_local',
            new_name='image',
        ),
    ]
