# Generated by Django 3.1.14 on 2023-04-15 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0009_auto_20230414_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='pokedex_num',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
