# Generated by Django 3.1.14 on 2023-04-15 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230416_0056'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pokemon',
            old_name='poke_image',
            new_name='poke_image_local',
        ),
        migrations.AddField(
            model_name='pokemon',
            name='poke_image_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
