# Generated by Django 3.1.14 on 2023-04-26 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0010_auto_20230426_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pokemon',
            name='pokedex_num',
        ),
    ]
