# Generated by Django 3.1.14 on 2023-04-27 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_remove_pokemon_pokedex_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to='', verbose_name='Путь к картинке на вашем устройстве')),
                ('strong_against', models.ManyToManyField(blank=True, null=True, to='pokemon_entities.ElementType')),
            ],
        ),
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.pokemon')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pokemon_entities.elementtype')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(through='pokemon_entities.PokemonElementType', to='pokemon_entities.ElementType'),
        ),
    ]
