# Generated by Django 3.1.14 on 2023-04-28 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon_entities', '0011_remove_pokemon_pokedex_num'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonElementType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Путь к картинке на вашем устройстве')),
                ('strong_against', models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType')),
            ],
        ),
        migrations.AddField(
            model_name='pokemon',
            name='element_type',
            field=models.ManyToManyField(blank=True, to='pokemon_entities.PokemonElementType'),
        ),
    ]
